/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package luces;

/**
 *
 * @author Yo
 */
public class luces extends javax.swing.JFrame {

    /**
     * Creates new form luces
     */
    public luces() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        chkO1Pri = new javax.swing.JCheckBox();
        chkO1Sec = new javax.swing.JCheckBox();
        chkO1Seg = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        chkO2Pri = new javax.swing.JCheckBox();
        chkO2Sec = new javax.swing.JCheckBox();
        chkO2Seg = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        chkO3Pri = new javax.swing.JCheckBox();
        chkO3Sec = new javax.swing.JCheckBox();
        chkO3Seg = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenActivacion = new javax.swing.JMenu();
        ItemMenuApagarTodas = new javax.swing.JMenuItem();
        ItemMenuEncenderTodas = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        MenuDia = new javax.swing.JMenu();
        ItemMenuDiaOficina1 = new javax.swing.JMenuItem();
        ItemMenuDiaOficina2 = new javax.swing.JMenuItem();
        ItemMenuDiaOficina3 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        ItemMenuDiaOficinaTodas = new javax.swing.JMenuItem();
        MenuNoche = new javax.swing.JMenu();
        ItemMenuNocheOficina1 = new javax.swing.JMenuItem();
        ItemMenuNocheOficina2 = new javax.swing.JMenuItem();
        ItemMenuNocheOficina3 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        ItemMenuNocheOficinaTodas = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        ItemNenuSalir = new javax.swing.JMenuItem();
        MenInfo = new javax.swing.JMenu();
        ItemMenuPrincipales = new javax.swing.JMenuItem();
        ItemMenuSecundarias = new javax.swing.JMenuItem();
        ItemMenuSeguridad = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        ItemMenuAcerca = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Oficina 1"));

        chkO1Pri.setText("Luz Principal");

        chkO1Sec.setText("Luz Secundaria");

        chkO1Seg.setText("Luz de Seguridad");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkO1Pri)
                    .addComponent(chkO1Sec)
                    .addComponent(chkO1Seg))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(chkO1Pri)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkO1Sec)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkO1Seg)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Oficina 2"));

        chkO2Pri.setText("Luz Principal");

        chkO2Sec.setText("Luz Secundaria");

        chkO2Seg.setText("Luz de Seguridad");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkO2Pri)
                    .addComponent(chkO2Seg)
                    .addComponent(chkO2Sec))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(chkO2Pri)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkO2Sec)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkO2Seg)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Oficina 3"));

        chkO3Pri.setText("Luz Principal");

        chkO3Sec.setText("Luz Secundaria");

        chkO3Seg.setText("Luz de Seguridad");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkO3Pri)
                    .addComponent(chkO3Sec)
                    .addComponent(chkO3Seg))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(chkO3Pri)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkO3Sec)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkO3Seg)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 141, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 154, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 142, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 141, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 143, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        MenActivacion.setText("Activación");

        ItemMenuApagarTodas.setText("Apagar Todas");
        MenActivacion.add(ItemMenuApagarTodas);

        ItemMenuEncenderTodas.setText("EncenderTodas");
        MenActivacion.add(ItemMenuEncenderTodas);
        MenActivacion.add(jSeparator1);

        MenuDia.setText("Dia");

        ItemMenuDiaOficina1.setText("Oficina 1");
        MenuDia.add(ItemMenuDiaOficina1);

        ItemMenuDiaOficina2.setText("Oficina 2");
        MenuDia.add(ItemMenuDiaOficina2);

        ItemMenuDiaOficina3.setText("Oficina 3");
        MenuDia.add(ItemMenuDiaOficina3);
        MenuDia.add(jSeparator4);

        ItemMenuDiaOficinaTodas.setText("Todas");
        MenuDia.add(ItemMenuDiaOficinaTodas);

        MenActivacion.add(MenuDia);

        MenuNoche.setText("Noche");

        ItemMenuNocheOficina1.setText("Oficina 1");
        MenuNoche.add(ItemMenuNocheOficina1);

        ItemMenuNocheOficina2.setText("Oficina 2");
        MenuNoche.add(ItemMenuNocheOficina2);

        ItemMenuNocheOficina3.setText("Oficina 3");
        MenuNoche.add(ItemMenuNocheOficina3);
        MenuNoche.add(jSeparator5);

        ItemMenuNocheOficinaTodas.setText("Todas");
        MenuNoche.add(ItemMenuNocheOficinaTodas);

        MenActivacion.add(MenuNoche);
        MenActivacion.add(jSeparator2);

        ItemNenuSalir.setText("Salir");
        MenActivacion.add(ItemNenuSalir);

        jMenuBar1.add(MenActivacion);

        MenInfo.setText("Info");

        ItemMenuPrincipales.setText("Principales");
        MenInfo.add(ItemMenuPrincipales);

        ItemMenuSecundarias.setText("Secundarias");
        MenInfo.add(ItemMenuSecundarias);

        ItemMenuSeguridad.setText("Seguridad");
        MenInfo.add(ItemMenuSeguridad);
        MenInfo.add(jSeparator3);

        ItemMenuAcerca.setText("Acerca de ...");
        MenInfo.add(ItemMenuAcerca);

        jMenuBar1.add(MenInfo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(luces.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(luces.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(luces.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(luces.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new luces().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemMenuAcerca;
    private javax.swing.JMenuItem ItemMenuApagarTodas;
    private javax.swing.JMenuItem ItemMenuDiaOficina1;
    private javax.swing.JMenuItem ItemMenuDiaOficina2;
    private javax.swing.JMenuItem ItemMenuDiaOficina3;
    private javax.swing.JMenuItem ItemMenuDiaOficinaTodas;
    private javax.swing.JMenuItem ItemMenuEncenderTodas;
    private javax.swing.JMenuItem ItemMenuNocheOficina1;
    private javax.swing.JMenuItem ItemMenuNocheOficina2;
    private javax.swing.JMenuItem ItemMenuNocheOficina3;
    private javax.swing.JMenuItem ItemMenuNocheOficinaTodas;
    private javax.swing.JMenuItem ItemMenuPrincipales;
    private javax.swing.JMenuItem ItemMenuSecundarias;
    private javax.swing.JMenuItem ItemMenuSeguridad;
    private javax.swing.JMenuItem ItemNenuSalir;
    private javax.swing.JMenu MenActivacion;
    private javax.swing.JMenu MenInfo;
    private javax.swing.JMenu MenuDia;
    private javax.swing.JMenu MenuNoche;
    private javax.swing.JCheckBox chkO1Pri;
    private javax.swing.JCheckBox chkO1Sec;
    private javax.swing.JCheckBox chkO1Seg;
    private javax.swing.JCheckBox chkO2Pri;
    private javax.swing.JCheckBox chkO2Sec;
    private javax.swing.JCheckBox chkO2Seg;
    private javax.swing.JCheckBox chkO3Pri;
    private javax.swing.JCheckBox chkO3Sec;
    private javax.swing.JCheckBox chkO3Seg;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    // End of variables declaration//GEN-END:variables
}
