/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vjv.pizza;

/**
 *
 * @author Yo
 */
public class Pizza extends javax.swing.JFrame {

    /**
     * Creates new form Pizza
     */
    
    public Pizza() {
        initComponents();
                 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonGroup = new javax.swing.ButtonGroup();
        grupotamaño = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        chkBacon = new javax.swing.JCheckBox();
        chkAnchoas = new javax.swing.JCheckBox();
        chkCebolla = new javax.swing.JCheckBox();
        chkPimiento = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        rbtnPequeña = new javax.swing.JRadioButton();
        rbtnMediana = new javax.swing.JRadioButton();
        rbtnFamiliar = new javax.swing.JRadioButton();
        btnTotal = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingredientes"));
        jPanel1.setToolTipText("");
        jPanel1.setName(""); // NOI18N

        chkBacon.setText("Bacon");

        chkAnchoas.setText("Anchoas");

        chkCebolla.setText("Cebolla");

        chkPimiento.setText("Pimiento");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkAnchoas)
                    .addComponent(chkCebolla)
                    .addComponent(chkPimiento)
                    .addComponent(chkBacon))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(chkBacon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkAnchoas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkCebolla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkPimiento)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tamaño"));

        grupotamaño.add(rbtnPequeña);
        rbtnPequeña.setText("Pequeña");
        rbtnPequeña.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbtnPequeñaStateChanged(evt);
            }
        });

        grupotamaño.add(rbtnMediana);
        rbtnMediana.setText("Mediana");
        rbtnMediana.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbtnMedianaStateChanged(evt);
            }
        });

        grupotamaño.add(rbtnFamiliar);
        rbtnFamiliar.setText("Familiar");
        rbtnFamiliar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbtnFamiliarStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtnPequeña)
                    .addComponent(rbtnMediana)
                    .addComponent(rbtnFamiliar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtnPequeña)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtnMediana)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnFamiliar)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        btnTotal.setText("Total");
        btnTotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTotalMouseClicked(evt);
            }
        });

        lblResultado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(btnTotal))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTotal)
                .addGap(18, 18, 18)
                .addComponent(lblResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnTotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTotalMouseClicked
        // TODO add your handling code here:
        int total= 0;
        
        if (rbtnPequeña.isSelected()) {
            total=total+100;
        }
        if (rbtnMediana.isSelected()) {
            total=total+150;
        }
        if (rbtnFamiliar.isSelected()) {
            total=total+200;
        }
        
        if (chkBacon.isSelected()){
            total=total+20;
        }
         if (chkAnchoas.isSelected()){
            total=total+15;
        }
          if (chkCebolla.isSelected()){
            total=total+10;
        }
         if (chkPimiento.isSelected()){
            total=total+14;
        }
        
        lblResultado.setText("El total de la pizza es "+ total );
    }//GEN-LAST:event_btnTotalMouseClicked

    private void rbtnPequeñaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbtnPequeñaStateChanged
        // TODO add your handling code here:
        if (rbtnPequeña.isSelected()) {
        rbtnMediana.setSelected(false);
        rbtnFamiliar.setSelected(false);
    }
    }//GEN-LAST:event_rbtnPequeñaStateChanged

    private void rbtnMedianaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbtnMedianaStateChanged
        // TODO add your handling code here:
        if (rbtnMediana.isSelected()) {
        rbtnPequeña.setSelected(false);
        rbtnFamiliar.setSelected(false);
    }
    }//GEN-LAST:event_rbtnMedianaStateChanged

    private void rbtnFamiliarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbtnFamiliarStateChanged
        // TODO add your handling code here:
        if (rbtnFamiliar.isSelected()) {
        rbtnPequeña.setSelected(false);
        rbtnMediana.setSelected(false);
    }//GEN-LAST:event_rbtnFamiliarStateChanged
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pizza().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup ButtonGroup;
    private javax.swing.JButton btnTotal;
    private javax.swing.JCheckBox chkAnchoas;
    private javax.swing.JCheckBox chkBacon;
    private javax.swing.JCheckBox chkCebolla;
    private javax.swing.JCheckBox chkPimiento;
    private javax.swing.ButtonGroup grupotamaño;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JRadioButton rbtnFamiliar;
    private javax.swing.JRadioButton rbtnMediana;
    private javax.swing.JRadioButton rbtnPequeña;
    // End of variables declaration//GEN-END:variables
}
